version: '3.8'

services:
  mysql:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-blockchain
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "exit 0"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
  mysql-test:
    image: mysql:8.0.23
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: go-blockchain-test
    cap_add:
      - SYS_NICE
    healthcheck:
      test: "exit 0"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
  server:
    build:
      context: ./docker/server
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3001:3001"
    volumes:
      - ./docker/server:/app
    restart: always
